### ISSUE TITLE
Unable to change body font

### ISSUE THREAD

**Issue by flyingdutchman** [godaddy-wordpress/primer-child-escapade#69]
Hello !

I am trying to change the font of the post, but none of the options in the customization panel seem to change it. Am I missing something ?

![opera instantane_2019-01-31_132441_flyindutchwebsite jcloud ik-server com](https://user-images.githubusercontent.com/26379223/52054124-c17da780-255b-11e9-97f6-713844c7b75d.png)

**Comment by EvanHerman** [comment]
Hi @flyingdutchman 

No, you are correct. I just did some testing and it does appear that the post font is locked to "Droid Serif". We'll have to push out an update to fix this.

In the meantime, you can manually set the font by adding some custom CSS to the 'Additional CSS' in the customizer.

Depending on your font, you can update the code snippet below:

```css
.entry-content p {
	font-family: "Merriweather";
}
```

Once you've added that to the 'Additional CSS' section of the customizer, the body font should update. As mentioned, we'll do some testing and push out an update to get this fixed.

Evan

**Comment by flyingdutchman** [comment]
The fix your proposed to me does not seem to work, the body of the post is still the one of the screenshot.
The content of the Additional CSS seems to be ignored.

![image](https://user-images.githubusercontent.com/26379223/52081253-0e806e80-259a-11e9-830c-2f96140eb4d8.png)

**Comment by EvanHerman** [comment]
Try the following:

```css
.entry-content p,
.entry-summary p,
.content p {
   font-family: "Merriweather";
}
```

I've tested and this appears to be working on my end.

**Comment by flyingdutchman** [comment]
This workaround works ! Thank you 👍

**Comment by dboehmer** [comment]
As WordPress now includes global controls for the font is the right path to just remove any font adjustment from this theme? If not, what else was your approach?

I’d like to see this actually fixed and would possibly provide a PR.

**Comment by dboehmer** [comment]
@EvanHerman Instead of explicitly setting values for font setting and redefining the same values over and over again, I prefer to apply global settings where possible. You can use the global WordPress font settings here.

```css
.entry-content p,
.entry-summary p,
.content p {
  font-family: inherit;
  font-size:   inherit;
  line-height: inherit;
}
```

**Comment by Sogolumbo** [comment]
Additionally I recommend:
``` css
.widget, 
.widget p, 
.widget ul, 
.widget ol {
    font-family: inherit;
    font-size:   inherit;
}
```
This will fix the serif font in the footer
